-- Supabase SQL Editor에서 이 파일 전체를 실행하세요.
-- 이 실습은 읽기용 시즌 테이블과 쓰기용 메시지 테이블을 만듭니다.

create table if not exists public.hachuping_seasons (
  id text primary key,
  sort_order integer not null unique,
  label text not null,
  title text not null,
  short_label text not null,
  theme text not null,
  tool text not null,
  mood text not null,
  point text not null,
  image text not null,
  description text not null,
  quote text not null,
  created_at timestamptz not null default now()
);

alter table public.hachuping_seasons enable row level security;

drop policy if exists "Anyone can read hachuping seasons" on public.hachuping_seasons;

create policy "Anyone can read hachuping seasons"
on public.hachuping_seasons
for select
to anon, authenticated
using (true);

grant select on public.hachuping_seasons to anon, authenticated;

insert into public.hachuping_seasons (
  id,
  sort_order,
  label,
  title,
  short_label,
  theme,
  tool,
  mood,
  point,
  image,
  description,
  quote
) values
(
  's1',
  1,
  '시즌 1',
  '시즌 1 하츄핑',
  'S1',
  '하트',
  '손거울',
  '사랑의 로열 티니핑',
  '첫 인상과 대표 실루엣',
  'https://static.wikia.nocookie.net/catchteenieping/images/c/c8/S1_%ED%95%98%EC%B6%94%ED%95%91_%EB%A0%8C%EB%8D%94%EB%A7%81_1.webp/revision/latest?cb=20260121143541&path-prefix=ko',
  '시즌 1 하츄핑은 클래식한 핑크 하트 콘셉트를 가장 선명하게 보여주는 시작점입니다. 손거울을 들고 다니며 사랑스럽고 다정한 분위기를 그대로 전달합니다.',
  '분명 근처에 티니핑이 있을 거야, 츄.'
),
(
  's2',
  2,
  '시즌 2',
  '시즌 2 하츄핑',
  'S2',
  '핑크 다이아몬드',
  '하프',
  '보석처럼 반짝이는 무드',
  '하트 장식이 보석으로 진화',
  'https://static.wikia.nocookie.net/catchteenieping/images/a/ac/%ED%95%98%EC%B8%84%EC%9E%89_%EC%8B%9C%EC%A6%8C_2.png/revision/latest?cb=20211024200626&path-prefix=ko',
  '시즌 2에서는 하트 장식이 보석처럼 반짝이며 더 화려한 느낌을 줍니다. 하프를 들고 등장해 동화적인 우아함이 강조됩니다.',
  '반짝이는 사랑 에너지가 한층 더 커진 시즌이야, 츄.'
),
(
  's3',
  3,
  '시즌 3',
  '시즌 3 하츄핑',
  'S3',
  '꽃',
  '향수',
  '꽃향기와 로맨틱 무드',
  '꽃 장식과 소녀스러운 실루엣',
  'https://static.wikia.nocookie.net/catchteenieping/images/5/53/S3_%ED%95%98%EC%B6%94%ED%95%91_%EB%A0%8C%EB%8D%94%EB%A7%81_1.png/revision/latest?cb=20260129061332&path-prefix=ko',
  '시즌 3 하츄핑은 머리의 꽃 장식과 향수병 소품이 중심입니다. 사랑스러운 이미지를 더 부드럽고 향기로운 감성으로 확장한 버전입니다.',
  '꽃처럼 달콤한 시즌 3 하츄핑은 보기만 해도 기분이 말랑해져.'
),
(
  's4',
  4,
  '시즌 4',
  '시즌 4 하츄핑',
  'S4',
  '베리 쿠키',
  '핸드벨',
  '디저트와 파티 무드',
  '딸기 쿠키 같은 장식 디테일',
  'https://static.wikia.nocookie.net/catchteenieping/images/1/1e/%ED%95%98%EC%B8%84%EC%9E%89_%EC%8B%9C%EC%A6%8C_4.png.png/revision/latest?cb=20260129061538&path-prefix=ko',
  '시즌 4는 베리 쿠키를 떠올리게 하는 디저트 장식이 포인트입니다. 핸드벨 소품과 함께 더 통통 튀는 파티 감성이 느껴집니다.',
  '딸기와 디저트 무드가 가장 진하게 묻어나는 건 바로 이 시즌이야.'
),
(
  's5',
  5,
  '시즌 5',
  '시즌 5 하츄핑',
  'S5',
  '스타',
  '글로우 퍼프',
  '우주빛 글로우 무드',
  '하트 대신 별 포인트가 강조',
  'https://static.wikia.nocookie.net/catchteenieping/images/1/12/%EC%8A%A4%ED%83%80%ED%95%98%EC%B8%84%ED%95%91.png/revision/latest?cb=20260206013014&path-prefix=ko',
  '시즌 5는 별과 글로우 무드가 핵심입니다. 핑크 톤을 유지하면서도 한층 더 판타지스럽고 우주적인 분위기로 확장됩니다.',
  '별빛이 더해진 하츄핑은 무드 자체가 반짝임 그 자체야.'
),
(
  's6',
  6,
  '시즌 6',
  '시즌 6 하츄핑',
  'S6',
  '프린세스',
  '요술봉',
  '프린세스 피날레 무드',
  '왕실풍 디테일과 화려한 소품',
  'https://static.wikia.nocookie.net/catchteenieping/images/9/91/%ED%95%98%EC%B8%84%ED%95%91_6%EA%B8%B0.png/revision/latest?cb=20260206012544&path-prefix=ko',
  '시즌 6 하츄핑은 프린세스 무드가 극대화된 형태입니다. 요술봉과 함께 등장하며 전체 실루엣이 더 화려하고 궁전풍 디테일을 갖습니다.',
  '프린세스 무드의 완성형, 마지막 카드다운 존재감이야.'
)
on conflict (id) do update set
  sort_order = excluded.sort_order,
  label = excluded.label,
  title = excluded.title,
  short_label = excluded.short_label,
  theme = excluded.theme,
  tool = excluded.tool,
  mood = excluded.mood,
  point = excluded.point,
  image = excluded.image,
  description = excluded.description,
  quote = excluded.quote;

create table if not exists public.hachuping_messages (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(btrim(nickname)) between 1 and 20),
  message text not null check (char_length(btrim(message)) between 1 and 160),
  season_id text references public.hachuping_seasons(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists hachuping_messages_created_at_idx
on public.hachuping_messages (created_at desc);

alter table public.hachuping_messages enable row level security;

drop policy if exists "Anyone can read hachuping messages" on public.hachuping_messages;
drop policy if exists "Anyone can insert hachuping messages" on public.hachuping_messages;

create policy "Anyone can read hachuping messages"
on public.hachuping_messages
for select
to anon, authenticated
using (true);

create policy "Anyone can insert hachuping messages"
on public.hachuping_messages
for insert
to anon, authenticated
with check (
  char_length(btrim(nickname)) between 1 and 20
  and char_length(btrim(message)) between 1 and 160
);

grant select, insert on public.hachuping_messages to anon, authenticated;
grant usage, select on sequence public.hachuping_messages_id_seq to anon, authenticated;
